name:                sappy
version:             0.1
github:              "heades/sappy"
license:             BSD3
author:              "Harley Eades III"
maintainer:          "harley.eades@gmail.com"
copyright:           "2022 Harley Eades III"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sappy#readme>

dependencies:
- base       >= 4.7    && < 5
- haskeline  >= 0.8    && < 0.9
- containers >= 0.6    && < 0.7
- QuickCheck >= 2.14   && < 2.15
- mtl        >= 2.2    && < 2.4

library:
  source-dirs: src

executables:
  sappy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - QuickCheck
    - sappy
